### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by flopon** [docupdater/docupdater#3]
Finally some remarks / suggestions:

- I find that prefixing all the environment variables with 'DOCUPDATER' weighed a little unnecessarily the configuration.
- I think you should be able to add a timezone configuration option.
- Just a personal opinion: A project begin with a name we remember! I think we can find better than "docupdater" (at least "dockupdater", there we wonder if we update some documentation)

Overall, great work, basically all my needs in container updating are fullfilled by you project !

**Comment by mathcantin** [comment]
1. I'm agree with you. At start it was to work around a problem with the cli a package. I will update that.
2. Consult the docs for help with timezone https://github.com/docupdater/docupdater/blob/master/docs/Frequently-Asked-Questions.md#timezone-configuration
3. I'll think about it

Thanks you

**Comment by flopon** [comment]
Thank you, I did not see that the configuration of the time zone was possible.

Works surprisingly well at home for a beta ;)

**Comment by mathcantin** [comment]
@flopon I remove DOCUPDATER prefix
